### PR TITLE
Binomial Lesson

### PR DESCRIPTION
**Pull request by monikasingh20**
I my teammate sakshi sharma was assigned binomial lesson by you, we have designed a  binomial lesson.
which includes text animation, gif animation , contents with proper ui design.

### CODE REVIEW

**Comment by monikasingh20** [comment]
@JessicaML please review it and suggest any changes .

**Comment by JessicaML** [comment]
Thanks for your work on the lesson! Please use the [style guide](https://docs.google.com/document/d/1ylqK2kmtucIEN8i6X8uWU3Rk_j1o2WWpaOcoMIptNZk/edit) and [template](https://drive.google.com/drive/folders/1rnpBAD3iyGnvUBQ6OxbHcIDNg4T6w7Rn) for colours, fonts and buttons.

**Comment by monikasingh20** [comment]
@JessicaML , I have change font ,color, button according to style guide, Please review it and suggest any changes .

**Comment by JessicaML** [comment]
Thanks Monika, the Fugaz and Space Mono fonts are not rendering for some reason. Can you also remove the blinking?

**Comment by monikasingh20** [comment]
@JessicaML i have removed blinking feature and both Fugaz and space mono font are also rendered.
please review it and suggest any other change need to be done.

**Comment by Sakshi183** [comment]
@JessicaML Please review this lesson and suggest if some changes are required .Our team has made some changes as suggested by you.

**Comment by JessicaML** [comment]
Thanks guys I'm having a think about this one. There is a lot of content   here so I think it might be worth breaking into 2 or even 3 lessons. The click handlers on the boxes no longer work. I think it's good to have a visual element but e need to design it ourselves. Do you mind if I get in touch with a designer to make some illustrations for the different kingdoms?

**Pull request closed without merging**
