### PR TITLE
stars galaxy lesson added

### PR DESCRIPTION
**Pull request by Paarmita**
Twinkling Stars Galaxy lesson added by CSS animations of night view.
Will it work or I could add galaxy background?
screenshot 1
New spiral galaxy added( three.js)
screenshot from 2018-05-24 23-02-37

### CODE REVIEW

**Comment by JessicaML** [comment]
This looks great! I think it would be better to include an interactive element. Maybe also some visual of a galaxy like this: https://www.google.nl/search?q=galaxy&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjM1LXS0e7aAhWHKewKHeroCFYQ_AUICigB&biw=809&bih=780

Perhaps you could play around with 3.js - see if its something you'd like to experiment with? 
https://threejs.org/examples/#webgl_interactive_cubes_gpu

**Comment by Paarmita** [comment]
@JessicaML I have a new idea to implement the galaxy in the spiral using three.js. So it would look really awesome on mouse rotations as it would be interactive. I am working on it and will let u know.

**Comment by Paarmita** [comment]
@JessicaML Plz review the new lesson done with three.js

**Comment by JessicaML** [comment]
This is great Paarmita! Well done!

**Pull request merged**
