### PR TITLE
group1 alkali metals lesson1 added

### PR DESCRIPTION
**Pull request by KanchanThareja**

### CODE REVIEW

**Comment by KanchanThareja** [comment]
@JessicaML  I have added the lesson for "Group 1 - The Alkali Metals" in the folder group1_alkaliMetals.
[animated.zip](https://github.com/JessicaML/ScienceMotion-Static/files/2808224/animated.zip)

Please view the screen recording for the lesson and suggest if any changes are required.

**Comment by KanchanThareja** [comment]
@JessicaML I have completely changed the visuals for the alkali metals lesson. Through this change i have tried to include better user interaction.
[final.zip](https://github.com/JessicaML/ScienceMotion-Static/files/2840448/final.zip)
Please review the changes.

**Comment by JessicaML** [comment]
Great, will take a look asap

**Comment by JessicaML** [comment]
Wow! Absolutely amazing! Thank you! :)

**Pull request merged**
