### PR TITLE
Average Speed Lesson

### PR DESCRIPTION
**Pull request by Sakshi183**
I have added the lesson for "average speed" in the folder speed.Please view the screen recording for the lesson and suggest if any changes are required.
[screen.zip](https://github.com/JessicaML/ScienceMotion-Static/files/1818217/screen.zip)

### CODE REVIEW

**Comment by JessicaML** [comment]
This looks awesome!
Can you use the colours from the style guide? https://docs.google.com/document/d/1ylqK2kmtucIEN8i6X8uWU3Rk_j1o2WWpaOcoMIptNZk/edit

**Comment by Sakshi183** [comment]
@JessicaML The colour in the text part only needs to be changed.Or do I require to change the colours in the animation part also .

**Comment by JessicaML** [comment]
Yes animation too

**Comment by JessicaML** [comment]
I think we could also make the peed of the car change when the user moves the mouse. We can have a call about how to implement this?

**Comment by Sakshi183** [comment]
@JessicaML I have made changes in the colour according to style guide.Please review the changes.
[screen_2.zip](https://github.com/JessicaML/ScienceMotion-Static/files/1821534/screen_2.zip)

**Comment by JessicaML** [comment]
Thanks so much! I will merge the PR in the next few weeks.

**Pull request merged**
